#pragma once
#include "wizard.user.h"

constexpr UINT MYWM_CREATE_WIZARD = WM_USER + 0x1001;
constexpr UINT MYWM_OPEN_WIZARD = WM_USER + 0x1002;
constexpr UINT MYWM_DESTROY_WIZARD = WM_USER + 0x1003;
constexpr UINT MYWM_INIT_WIZARD = WM_USER + 0x1004;
constexpr UINT MYWM_UPDATE_WIZARD = WM_USER + 0x1005;
constexpr UINT MYWM_SET_WIZARD_VALUE = WM_USER + 0x1006;
constexpr UINT MYWM_GET_WIZARD_HANDLE = WM_USER + 0x1007;
constexpr UINT MYWM_DELETE_WIZARD = WM_USER + 0x1008;
constexpr UINT MYWM_STEP_WIZARD_VALUE = WM_USER + 0x1009;

